<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0-browser</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
	  <!-- Disables the IL trimmer entirely for the application -->
	  <PublishTrimmed>false</PublishTrimmed>
	  <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.JSInterop" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />

    <!-- Force compatible SkiaSharp WebAssembly versions (versions defined in Directory.Packages.props) -->
    <PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.WebAssembly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SWSMonitor\SWSMonitor.csproj" />
    <ProjectReference Include="..\DataLibrary\DataLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\errorInterop.js">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

	<Target Name="UpdateBaseHref" BeforeTargets="BeforeBuild" Condition="'$(Configuration)' == 'Debug'">
		<PropertyGroup>
			<IndexHtmlPath>$(ProjectDir)wwwroot\index.html</IndexHtmlPath>
			<!-- Use '/' for local builds, or custom path for production/publishing -->
			<NewBaseHref Condition="'$(Configuration)' == 'Debug'">/</NewBaseHref>
			<NewBaseHref Condition="'$(Configuration)' == 'Release'">/SWSMonitor/</NewBaseHref>
		</PropertyGroup>

		<Message Text="Setting base href to '$(NewBaseHref)' for $(Configuration) build..." Importance="High" />

		<!-- PowerShell command to find and replace the base href tag 
		<Exec Command="powershell -Command &quot;(Get-Content '$(IndexHtmlPath)') -replace '&lt;base href=\&quot;.*\&quot;\s*/?&gt;', '&lt;base href=\&quot;$(NewBaseHref)\&quot; /&gt;' | Set-Content '$(IndexHtmlPath)'&quot;" />
		-->
	</Target>

</Project>
