<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	  <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
	  <!-- Disables the IL trimmer entirely for the application -->
	  <PublishTrimmed>false</PublishTrimmed>
	  <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>

  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Browser" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="DynamicData" />
    <PackageReference Include="FluentAvaloniaUI" />
    <PackageReference Include="Google.Apis.Oauth2.v2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.JSInterop" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\DataLibrary\DataLibrary.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <AvaloniaResource Update="Assets\Login-Door.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
  </ItemGroup>
</Project>
